<?php
 // module/Livre/view/livre/livre/index.phtml:


 $title = 'My livres';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('livre', array('action'=>'add'));?>">Add new livre</a>
 </p>

 <table class="table">
 <tr>
     <th>Titre</th>
     <th>Auteur</th>
     <th>Moyenne</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($livres as $livre) : ?>
 <tr>
     <td><?php
     echo $this->escapeHtml($livre->title);
     ?></td>
     <td><?php 
     echo $this->escapeHtml($livre->auteur);
     ?></td>
     <td><?php 
         echo $critiqueTable->getAverageMark($livre->id);
     ?></td>
     <td>
         <a href="<?php echo $this->url('livre',
             array('action'=>'edit', 'id' => $livre->id));?>">Edit</a>
         <a href="<?php echo $this->url('livre',
             array('action'=>'delete', 'id' => $livre->id));?>">Delete</a>
         <a href="<?php echo $this->url('livre',
             array('action'=>'critique', 'id' => $livre->id));?>">Criticize</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>


