<?php
 // module/Livre/view/livre/livre/index.phtml:

 $title = 'My livres';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('livre', array('action'=>'add'));?>">Add new livre</a>
 </p>

 <table class="table">
 <tr>
     <th>Title</th>
     <th>Artist</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($livres as $livre) : ?>
 <tr>
     <td><?php
              var_dump($livres);
     echo $this->escapeHtml($livres->title);?></td>
     <td><?php echo $this->escapeHtml($livres->artist);?></td>
     <td>
         <a href="<?php echo $this->url('livre',
             array('action'=>'edit', 'id' => $livres->id));?>">Edit</a>
         <a href="<?php echo $this->url('livre',
             array('action'=>'delete', 'id' => $livres->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>