<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        <?php
        // put your code here
        ?>
        <!-- //module/SanAuth/view/san-auth/success/index.phtml -->
        Login Success.
        <br />

        <a href="<?php echo $this->url('login/process', array('action' => 'logout')); ?>">Logout</a>
    </body>
</html>
